### ISSUE TITLE
Refactoring and cleaning

### ISSUE THREAD

**Issue by ben-kaufman** [cryptoadvance/specter-desktop#134]
Now that Specter is quite stable, there are many parts of the code which could use some refactoring. I'll list here the points which I'm already aware of and will continue to add based on comments here/ other things I notice.

- [x] Remove `nwjs` - this was an old experiment that is not used anymore). - (#135)
- [x] Break down `logic.py` into smaller files - this file has grown pretty huge and could be broken down into its composing classes - which would make it more readable and organized. - (#160)
- [x] Make reusable UI components - We currently have a lot of duplicated code in the front end, which we could turn into Jinja macros/ Custom elements - (#136).
- [x] Refactor frontend - In addition to using components, there is much old code that could be removed/ rewritten more nicely - (#136).
- [x] Refactor logic classes - Currently, these classes (`WalletManager`, `DeviceManager`, `Wallet`, `Device`) are somewhat unstructured, the managers aren't exactly a list nor an object, and the wallet contains some unnecessary data and uses a `_dict` instead of properly defining its attributes. We could refactor these classes to be better specified, more readable, and optimized. - (#160)
- [x] Connect wallet class with the devices - Currently, a wallet is completely separated from the devices it uses. For example, when deleting a device, the wallet will still remain. We should connect them and make them "aware" of each other. - (#160)
- [x] Refactor HWI - The current code we use for HWI is somewhat messy and requires unnecessary extra steps from the user. This refactoring is part of #131. (#143)
- [x] Structure Files - Files today (both front and back end) are somewhat disorganized, we could probably structure them better into directories in a way easier to reason about and navigate - (frontend: #136, backend: #160).
- [x] Remove Vue - We barely use Vue in the frontend, and where we do it's not hard to replace it with Jinja + JS. We should probably consider removing it, as it doesn't make sense to have it if we barely use it - (#136, #141).
- [x] Improve error handling - We use a lot of `try/catch` through the codebase, but in many points we just return `None` or print something or just `pass`. We should refactor those parts to send the user a proper error message/ page (maybe with an option to copy/ report the logs). - (#139, #156, #160)
- [ ] More testing - Currently our tests for Specter are quite scanty, we should probably add much more coverage of the code.

Please comment below with everything I should add to the list.

(_Update:_ Note that I edit this as stuff change.)

**Comment by stepansnigirev** [comment]
I agree with most of the points, one thing that worries me is this one:

> Replace Jinja with Vue - There are many places in which we use Jinja but it would probably be better to use Vue. This will make the frontend code more consistent and readable and would allow us to utilize many Vue features not available with Jinja.

Normally when you load a page with vue it takes a little bit of time to load before the content is properly displayed. As we mostly use forms and POST requests to transition between pages, it will result in glitches of the UI.
I see two ways to handle that: either we hide content until it is loaded, or we switch to vue routes and one-page app with REST API (and potentially websockets) for backend-frontend communication.

Vue routes makes the app monolithic, but more responsive. API of Vue is not very different from the one of Jinja, so the transition wouldn't be too hard. The benefit is that we don't need to run `specter.check()` for everything on every request - this function makes many RPC calls to update all balances etc... We can also think about ZMQ subscriptions to bitcoind and notify the user for incoming transactions, sync progress etc.

Let's start with small changes, introduce a few new components, and meanwhile, we can experiment on HWI bridge on how Vue app would look like.

**Comment by ben-kaufman** [comment]
Ok, we could skip that for now. I'm not sure really what would be the optimal way of integrating Vue and Flask, so I will try to read on that meanwhile.

**Comment by ben-kaufman** [comment]
So I've looked into the frontend code to see how we could better restructure it, so here are some thoughts on the use of Vue.

The current architecture is something like 95%+ Jinja, 5% Vue. This is somewhat weird, especially since they both have many overlapping functionalities and it's very unclear when to use which.
Also, the backend code and frontend are very strongly connected. The `controller.py` contains quite a lot of logic and transfers data directly to the frontend with Jinja. This makes using Vue in a proper way for larger parts of the app quite hard. One thing, for example, is passing data between components and the page. When we use the Jinja `include` everything is accessible automatically, but if we'll use Vue now we'll have to pass data with `props` which is less nice.
Regarding how we use Vue right now, it seems to me somewhat messy. We just instantiate it every time for every element and we don't really have any pattern of how to use it and where. We also don't use NPM, or even most features of Vue like Router, State management etc., but without that using Vue is somewhat crippled.

So the approach I think currently would be best is to focus on using Jinja to clean the code - in a similar way to how the `wallet_menu.html` was refactored into its own file. I think right now if we don't change the current architecture, using Jinja would be much better than Vue components.
For the JS, I think we should add JQuery to use instead of a lof of vanilla JS code like `document.getElementById` and the likes.

Does this make sense? Not sure I explained it very clearly so please ask if that's not clear.

**Comment by stepansnigirev** [comment]
Vue was introduced only recently and the idea was to keep it on the component level. So most of the stuff is rendered by jinja and does not change.
I am strongly against npm, because it introduces the dependency hell, and until now we were able to work without npm whatsoever.
I don't see the benefits of using jquery over vanilla javascript. `document.getElementById` looks more clear to me than `$("#blah")` or whatever they are using. I think vanilla js is good if used correctly. The js code we have can be definitely refactored, but I think we can do it without introducing jquery. For example, we can use [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) instead of httprequest ugliness we have now.

What do you think about [custom components](https://developer.mozilla.org/en-US/docs/Web/Web_Components)? They might solve the problem - we would not need to instantiate Vue, or even could drop Vue completely.

**Comment by stepansnigirev** [comment]
> So the approach I think currently would be best is to focus on using Jinja to clean the code - in a similar way to how the wallet_menu.html was refactored into its own file.

Agree. I think we are also not using many interesting features of jinja - they also have something similar to components (macros?).

**Comment by ben-kaufman** [comment]
Regarding NPM, I'm also against adding it. I'm used to it personally but in this project, it's probably unnecessary and would just introduce more complexity and security risks.

Regarding jQuery, I guess it's just a personal preference, so not necessarily needed. Also, I agree we could refactor much of the JS code without that, so will look into it to.

I'm still relatively new to Jinja, so I'm not too familiar with its more advanced features. Macros seem like a much better way than Vue components in our case, though I'm still trying to understand how is it different from using `include` (at least for our needs).

**Comment by stepansnigirev** [comment]
Macros can have parameters, so you can pass a wallet dict to it, and it will render a component for this particualr wallet (for example display or not a QR code or download PSBT button if Specter / CC are used).
Include is static - it just renders a piece of code without parameters.

I think for sidemenu include is perfect as it doesn't need much info (only currently selected page),
but for a component like transaction list element, macros might be better. I am also new to that, so let's learn together :)

**Comment by ben-kaufman** [comment]
Sounds good :) So I'll start by trying to move some reused elements into macros.

**Comment by stepansnigirev** [comment]
I was experimenting over the weekend with hwibridge, and I found a few interesting ways how we can refactor our codebase.

## Custom elements

Custom elements look pretty interesting. They are supported by all major browsers (maybe except Edge), and all the code is nicely isolated from everything else. They don't require any web framework, so we could get rid of vue with them.
Here, for example, a QRcode component ported from vue component that @gorazdko made to custom elements:
https://github.com/stepansnigirev/hwibridge/blob/master/src/templates/components/qrcode.html

Then, to use it we only need to make sure that `qrcode.html` is included in jinja template, and use `<qr-code value="blah"></qr-code>` component wherever we need it. It also works fine with vue or vanilla javascript - it has observers that properly changes the element when content is changed.

## JSON-RPC for JS API

Another thing I tried is on the backed side. I made HWI API in JSON-RPC format, this means that all javascript code related to HWI would need to access only a single endpoint, and I think it's pretty convenient. It also allows isolation of the HWIBridge component to a single class, that doesn't even need to know anything about flask and our webapp, and in flask we only pass through the requests to the class. When we want to extend functionality of the class we just introduce new methods there and in the javascript, no need to touch the server itself.
Here is the route for `/hwi` endpoint: https://github.com/stepansnigirev/hwibridge/blob/master/src/server.py#L23-L30
Here is the HWIBridge class implementation and JSONRPC parent class:
https://github.com/stepansnigirev/hwibridge/blob/master/src/hwibridge/logic.py#L63

What do you guys feel about that? Does it make sense to use this structure? Anything that can be changed or improved?

**Comment by ben-kaufman** [comment]
Custom elements look interesting. 
For now, in #136 I used Jinja `include` and `macros` to make components. I think it makes more sense for the "static" elements to use that as it seems simpler. But for the QRCodes and the coin selection feature, where we use Vue for dynamic UI changes I think it makes more sense indeed to use Custom Elements.

The JSON-RPC looks really nice. Seems like a very good solution to me.
(Just as a small comment  I would recommend separating each class into its own file, just to make it more organized.)

**Comment by stepansnigirev** [comment]
I think it would be also nice to split the settings screen, now it is pretty large already.
We can do a top menu similar to wallet screens with different submenus:

- Bitcoin Core
- Authentication
- HWI bridge
- Miscellanous

Then in multi-user case Bitcoin Core config would be unavailable for normal users, and admin could manage users in the Authentication section.

**Comment by ben-kaufman** [comment]
Closing now as all was implemented and tests coverage has its own issue #244
